In [1]:
import pandas as pd

data = pd.read_csv('/home/serao/violence_detection/violence-detection/log/double/version_0/metrics.csv')
df = data[['epoch','val_loss', 'val_acc']]
df = df.dropna()
df

    epoch  val_loss   val_acc
1     0.0  0.379312  0.843537
4     1.0  0.331900  0.853741
7     2.0  0.318270  0.870748
10    3.0  0.294529  0.882653
13    4.0  0.285911  0.872449
16    5.0  0.287745  0.880952
19    6.0  0.279790  0.891156
22    7.0  0.286404  0.882653
25    8.0  0.273048  0.891156
28    9.0  0.271189  0.882653
31   10.0  0.298948  0.894558
34   11.0  0.290498  0.884354
37   12.0  0.273795  0.899660
40   13.0  0.270687  0.896259
43   14.0  0.285217  0.899660
46   15.0  0.290210  0.891156
49   16.0  0.297664  0.889456
52   17.0  0.280600  0.894558
55   18.0  0.287764  0.896259
58   19.0  0.282265  0.891156
61   20.0  0.300878  0.892857

In [2]:
df2 = data[['epoch','train_loss', 'train_acc']]
df2 = df2.dropna()
df2

    epoch  train_loss  train_acc
2     0.0    0.584398   0.718659
5     1.0    0.392113   0.822886
8     2.0    0.340368   0.867347
11    3.0    0.326902   0.862974
14    4.0    0.246401   0.907434
17    5.0    0.258681   0.897959
20    6.0    0.216841   0.922741
23    7.0    0.210320   0.913994
26    8.0    0.192975   0.927114
29    9.0    0.170756   0.935860
32   10.0    0.190110   0.930029
35   11.0    0.126138   0.956268
38   12.0    0.141130   0.948251
41   13.0    0.137737   0.944606
44   14.0    0.130869   0.954082
47   15.0    0.138779   0.944606
50   16.0    0.115345   0.962099
53   17.0    0.130036   0.945335
56   18.0    0.092179   0.976676
59   19.0    0.075698   0.972303
62   20.0    0.088121   0.969388